#Como Que Resolve?

Eu recomendo rodar o script do building na máquina do Google Colab

In [44]:
! python3 Building.py saida.txt

Traceback (most recent call last):
  File "/content/Building.py", line 49, in <module>
object address  : 0xfbefd472080
object refcount : 3
object type     : 0xa274e0
object type name: KeyboardInterrupt
object repr     : KeyboardInterrupt()
lost sys.stderr
^C

In [63]:
! du -sh enigma2.csv

308M	enigma2.csv

Carrega o dataset, já que há 15kk (ou um tamanho de 308MB) de registros

In [47]:
import pandas as pd

In [48]:
df = pd.read_csv('enigma2.csv', sep=';')

In [49]:
df.head()

  data-acesso       quem-acessou  quantidade-de-acessos
0     2011-09            Buffalo                     16
1     2025-03             Collie                     12
2     2016-07            Tuatara                     13
3     2012-07     Dogo Argentino                      4
4     2021-04  Fire-Bellied Toad                     14

Filter : Selecione os acessos de Outubro de 2025

In [50]:
out = df[df['data-acesso'] == '2025-10']
display(out)

         data-acesso         quem-acessou  quantidade-de-acessos
272          2025-10  Cross River Gorilla                     10
863          2025-10     Poison Dart Frog                     11
990          2025-10     White Rhinoceros                      6
1184         2025-10                Sable                     16
1385         2025-10    Radiated Tortoise                     16
...              ...                  ...                    ...
14999753     2025-10           Water Vole                     10
14999803     2025-10      Snapping Turtle                      5
14999918     2025-10          Jack Russel                      1
14999928     2025-10        Blue Lacy Dog                     17
14999979     2025-10     White Rhinoceros                      7

[73824 rows x 3 columns]

In [51]:
out.shape[0]

73824

Encontre aquele que teve mais acessos : Nesse caso, Vampire Squid (Esse é o codenome do hacker)

In [60]:
out.groupby(
    'quem-acessou'
).agg({'quantidade-de-acessos' : sum}).sort_values(by='quantidade-de-acessos', ascending=False)

/tmp/ipython-input-3393388328.py:3: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  ).agg({'quantidade-de-acessos' : sum}).sort_values(by='quantidade-de-acessos', ascending=False)

                         quantidade-de-acessos
quem-acessou
Vampire Squid                             8486
Cow                                       8411
Dog                                       8348
Saiga                                     8300
British Timber                            8263
...                                        ...
Fire-Bellied Toad                         7189
Teddy Roosevelt Terrier                   7141
Blue Whale                                7107
Birman                                    6873
Bluetick Coonhound                        6832

[100 rows x 1 columns]